---
driver:
  name: docker
platforms:
  - name: Ubi8
    image: ubi8-python:v1
    privileged: true
    command: /usr/sbin/init
    registry: false
    pre_build_image: true

  - name: Debian11
    image: debian-python:11.9
    pre_build_image: true
    privileged: true
